#!/bin/bash

echo "🌟 Configuración de Cloudinary para MyHomeTech"
echo "============================================="
echo ""
echo "📝 Sigue estos pasos para configurar Cloudinary:"
echo ""
echo "1. Ve a https://cloudinary.com y crea una cuenta gratuita"
echo "2. Una vez registrado, ve a tu Dashboard"
echo "3. Copia los siguientes valores:"
echo "   - Cloud Name"
echo "   - API Key" 
echo "   - API Secret"
echo ""
echo "4. Actualiza el archivo apps/backend/dev.environments con tus credenciales:"
echo "   CLOUDINARY_CLOUD_NAME=tu_cloud_name"
echo "   CLOUDINARY_API_KEY=tu_api_key"
echo "   CLOUDINARY_API_SECRET=tu_api_secret"
echo ""
echo "5. Ejecuta la migración de base de datos:"
echo "   cd apps/backend && npm run typeorm migration:run"
echo ""
echo "6. Reinicia el servidor backend:"
echo "   npm run start:dev"
echo ""
echo "✅ Beneficios de Cloudinary:"
echo "   • 25GB de almacenamiento gratuito"
echo "   • CDN global para carga rápida"
echo "   • Optimización automática de imágenes"
echo "   • Transformaciones en tiempo real"
echo "   • Backup automático"
echo ""
echo "🚀 ¡Listo! Ahora las fotos se guardarán en la nube y se cachearán localmente."